# Generated by Django 5.0.6 on 2024-08-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
