# Generated by Django 5.0.6 on 2024-08-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_cruduser_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='sulg',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
