# Generated by Django 5.0.6 on 2024-08-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_cruduser_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='sulg',
            new_name='slug',
        ),
    ]
